### PR TITLE
Keep an eye open, im not changing code here, just sprite

### PR DESCRIPTION
**Pull request by shaneNum**
Careful and be vigilant we dont want trouble

### CODE REVIEW

**Comment by shaneNum** [comment]
what to do?

**Comment by GMugXD** [comment]
Confused on how to merge it

**Comment by GMugXD** [comment]
im pretty surr you have to open a pull request onnthe screen of qw-mod

**Comment by shaneNum** [comment]
dude
check your own
we did it siddway lmaooo

**Comment by shaneNum** [comment]
i will not merge pull quest
check your pullrequest

**Pull request closed without merging**
